### PR TITLE
Add task list component

### PR DESCRIPTION
**Pull request by somyasubham9**
Fixes #issue-number

**Description**

**Checklist**

- [ ] I have performed a self-review of my code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added the necessary label (patch/minor/major - If package publish
      is required).
- [ ] I have followed the suggested description format and styling.

**Reviewers**

### CODE REVIEW

**Comment by fyrepenguin** [comment]
The task list is not working for updating the status

**Comment by somyasubham9** [comment]
Sir I didn't get it . Like in which part if you can tell me then I can configure it.

**Comment by fyrepenguin** [comment]
Never mind, it's an issue on the tiptap side and is related to browser compatibility. [https://github.com/ueberdosis/tiptap/issues/3371](https://github.com/ueberdosis/tiptap/issues/3371). 
We might have to update it later.

**Comment by somyasubham9** [comment]
Ok Sir

**Pull request closed without merging**
